### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by cibermanchego** [nccgroup/Winpayloads#22]
Hi there, 
I updated today, and now I can't start the tool:

user@evilginx:~/tools/Winpayloads$ sudo ./WinPayloads.py 
Traceback (most recent call last):
  File "./WinPayloads.py", line 5, in <module>
    from lib.menu import *
  File "/home/user/tools/Winpayloads/lib/menu.py", line 4, in <module>
    from generatepayload import *
  File "/home/user/tools/Winpayloads/lib/generatepayload.py", line 8, in <module>
    from sockets import *
ImportError: No module named sockets

I tried in Kali and Ubuntu 16.04, both same error.

**Comment by Charliedean** [comment]
Should be fixed now.
Thanks

**Comment by cibermanchego** [comment]
I made a setup.sh -r
Still the same error.
I deleted everything and reinstall from scratch, but no luck either.

[Edit]
It works in a Debian 9 32bits. The other machines that fail are 64bit.
